### ISSUE TITLE
"Total time logged" disappeared

### ISSUE THREAD

**Issue by arnisjuraga** [harvesthq/platform#18]
Hi!

From pop-up timer window disappeared "Total Time Logged" for issue. 
Previously it was visible somewhere around this red block:

![image](https://cloud.githubusercontent.com/assets/2185289/6393181/a0a0f8c4-bdd0-11e4-8187-4a5f003e608d.png)

**Comment by adunkman** [comment]
Hey @arnisjuraga! 

Thanks for reporting this issue — and sorry for the inconvenience! It’s definitely a bug and we’re looking at getting the total time tracked back right away. I’ll update this issue when it’s been resolved. 

Until then, the total time tracked is still visible on the Stop Timer page (although it’s a little less convenient).

**Comment by adunkman** [comment]
Hello again @arnisjuraga!

We’ve just released an update to Harvest which shows the total time tracked on the Start Timer dialog once again — sorry for the inconvenience!

**Comment by arnisjuraga** [comment]
Tha same here - That was fast! :)
