### ISSUE TITLE
"End Time" automatically converted to "current time", if character entered, but timer not stopped

### ISSUE THREAD

**Issue by arnisjuraga** [harvesthq/platform#19]
In harvestapp.com online, if I set Start time in history and input dot (.) symbol in End Time field, with saving Harvest will automatically convert End Time value to Current Time value and **stop timer**.

So, it is easy to save last spent time without entering exact  current time value.

Now in platform - it does not stop timer.
I liked previous functionality. Will it be fixed, or I can enter "End Time" value differently?

 
![image](https://cloud.githubusercontent.com/assets/2185289/6396712/b2a6c2f2-bde8-11e4-8a01-76e253ad773d.png)

**Comment by adunkman** [comment]
Hey @arnisjuraga, thanks for reporting this! Yes, this is a bug — we should be understanding “.” as the current time, as we do in the web version of Timesheets. 

I’ll update this issue when it’s fixed!

**Comment by adunkman** [comment]
… well, that went faster than expected! Just released an update which restores “.” = now. 

Be sure to let us know if the issue pops up again — and thanks for letting us know in the first place!

**Comment by arnisjuraga** [comment]
Whou! This was fast! :)
