### ISSUE TITLE
Add date field

### ISSUE THREAD

**Issue by FreakTheMighty** [harvesthq/platform#26]
I would like the ability to change the date from within the harvest widget. Currently, using a plugins such as https://github.com/omigos/HubHarvester, I end up creating the time log, then visiting harvest to edit the date.

See this issue https://github.com/omigos/HubHarvester/issues/16

**Comment by adunkman** [comment]
Hey @FreakTheMighty, thanks for the feedback! 

It’s not something that’s in our current plans, but we’ll keep it in mind for the future. 

Just curious — what is your workflow like? I used the [Harvest for Chrome](https://chrome.google.com/webstore/detail/harvest-time-tracker/fbpiglieekigmkeebmeohkelfpjjlaia) extension to track time in GitHub, and I just track time as I’m working on things (so I don’t ever need to change the date myself).

**Comment by FreakTheMighty** [comment]
Hi @adunkman , I use https://github.com/omigos/HubHarvester. This allows me to track time in either github or huboard. While I know I *should* track my time as I go, sometimes I end up tracking time after the fact. For example, I may spend the day working on a task, then come in the following morning to log time for it.

I prefer logging time via the plugin because it links to our github issues. While harvest has a great timecard UI, it doesn't provide away to link to github issues.

Does harvest have any public view of their roadmap?

**Comment by adunkman** [comment]
Gotcha! Thanks for the information! :) /cc @katierose4

> Does harvest have any public view of their roadmap?

No, we don’t — we’ve found that over time, many people perceive a roadmap as a list of things that we’ve promised to work on. We’ve also found that it’s most efficient and correct to change what we are working on as we learn more about each project we take on — which means that our rough roadmap changes pretty frequently. As a result, we generally don’t discuss our plans — but you can be assured that we’re constantly working to improve Harvest in both big and small ways.
