### ISSUE TITLE
Select a default project

### ISSUE THREAD

**Issue by MowWow** [harvesthq/platform#28]
Hi,

I'm trying to integrate the harvest button in our issue tracker. I want to be able to setup the selected project when the button is clicked, so the default project could be the one the actual displayed issue belong to. 
Unfortunately the is no "project" parameter in the data-item section. So i'm trying to do it with jQuery, do you think it is possible to change the default value of the select menu of the project field when the popup is showed ? Cause the select menu is hidden by default,..

Thanks

**Comment by langeland** [comment]
I got the same issue..

**Comment by MowWow** [comment]
Hmm, any news ? do you think it is possible to have this option ?

It could be an optionnal field project in the data-item, where we have to put the Project Code for example ?

**Comment by hiddenl00p** [comment]
+1

**Comment by TheMonkeyz** [comment]
+1 too

**Comment by katierose4** [comment]
@MowWow @langeland @hiddenl00p @TheMonkeyz Thanks for passing along this feedback! We don't have near term plans to add the option to change the default value of the project field. I'd be curious to hear more about why you're interested in this, if you don't mind sharing. Thanks!

**Comment by MowWow** [comment]
Hi Katie,

Thanks for your feedback!

In out company, we integrated the Harvest Button in our issue tracker (Redmine). 
So everytime a developer works on an issue, he uses the harvest button to log his time. The description contains by default the issue's title. But our developers always forget to set the right project, as they think the project field contains the right projet by default.

Every monday, we have to check all the developpers last week's timesheets to fix all those logs where the developers forgot to set the right project.

If we had a project field in the data-item, we could set by default the right project

Thanks

**Comment by MowWow** [comment]
Is it possible at least to make the project field always empty by default ? To force the employees to choose the right project. We have multiple errors in all the timesheets every week, and it's always the same error, the project field doesn't contain the right project.

Thanks a lot,

**Comment by mpetito** [comment]
This is really needed! We're using this integration to put Harvest into Visual Studio Team Services, and it'd be great to pre-populate the Project field.

**Comment by binarymonkey84** [comment]
Have wanted this feature for about 2 years! Was hoping it would be added so came back to check, but doesn't appear to have materialised :(

I think the use case is pretty clear - we too have lots of time entries being added against the wrong projects, as users assume since the timer is embedded inside the app, it will select the right project.

Surely this is a simple one to implement and wouldn't break any existing integrations. It would be awesome to have this added please!

**Comment by pusewicz** [comment]
This has been addressed by a recent change and it's now possible to choose the preselected project by either its code (`default_project_code`) or name (`default_project_name`).

The updated documentation is available for both [widget](https://github.com/harvesthq/platform/blob/master/widget.md) and [button](https://github.com/harvesthq/platform/blob/master/button.md).

Thank you! 🎉

**Comment by MowWow** [comment]
Yeahhhhhhhhhhhhhhh! Thanks a lot!
