### ISSUE TITLE
Button doesn't work when hosting application on a non-standard port.

### ISSUE THREAD

**Issue by tm-lmathieu** [harvesthq/platform#30]
We have a Redmine instance on port 8085. https://platform.harvestapp.com/assets/platform.js tries to contact https://platform.harvestapp.com:8085, which won't work.

We found a dirty workaround.  We are hosting our own platform.js and source it from our server.  I removed the characters at position 1219 and 1220 ("+r")  and now it works properly.

**Comment by braddunbar** [comment]
Thanks for telling us about this @tm-lmathieu! I'll have it fixed up shortly.

**Comment by tm-lmathieu** [comment]
Thank you!

**Comment by braddunbar** [comment]
Just shipped a fix, please let me know if it doesn't work the way you expected. And again, thanks for letting us know about this! :smiley_cat:

**Comment by tm-lmathieu** [comment]
Seems to be working just fine!  Thank a lot!
