### ISSUE TITLE
Query by group and item id

### ISSUE THREAD

**Issue by thomasmcgee** [harvesthq/platform#31]
Hello,
If we were to use your widget in our own application are we allowed to query your api with the group_id and item_id? There is no documentation for this here:  https://github.com/harvesthq/platform/blob/master/widget.md 
thank you!

**Comment by katierose4** [comment]
Hi Thomas,

Thanks for writing in! I believe we spoke about this in more detail over email. I've made note of your feedback so I'm going to close this for now. 

Thanks,
Katie

**Comment by thomasmcgee** [comment]
Yep, that's great, thanks!

On Wed, Feb 10, 2016 at 11:20 AM, Katie Rose <notifications@github.com>
wrote:

> Hi Thomas,
>
> Thanks for writing in! I believe we spoke about this in more detail over
> email. I've made note of your feedback so I'm going to close this for now.
>
> Thanks,
> Katie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harvesthq/platform/issues/31#issuecomment-182456784>.
>



-- 
Thomas McGee | Co-Founder
(732) 741 7370 x116
