### ISSUE TITLE
Widget currently broken

### ISSUE THREAD

**Issue by tanc** [harvesthq/platform#33]
Hi there,

We had a working widget embedded in our internal site but its currently not working. I've contacted Harvest support but not heard anything back from them. Let me know if you need more info.

![atrium_update___comments_in_tracker___agile_support](https://cloud.githubusercontent.com/assets/76320/14988459/ccef522a-114b-11e6-8534-079c3047b358.png)

**Comment by adunkman** [comment]
Thanks for the info — I’ll be in touch through your support email!
