### ISSUE TITLE
Existing group id is not recognized / preselected

### ISSUE THREAD

**Issue by janmyszkier** [harvesthq/platform#36]
If I pass:
 {"id":"12","name":"Project Name"}
(Where "12" and "Project Name" are available in my harvest account)

and the group (Project) already exist in my account, it should be a pre-selected entry. 

Currently the button opens the window and suggests me adding new entry under the same name.
I consider this a bug because this doesn't allow integrations on already-existing setups and render that button unusable.

**Comment by janmyszkier** [comment]
@evanwalsh / @adunkman / @rbright  :point_up:

**Comment by adunkman** [comment]
We don’t currently match on the string names, only on the ID — and the ID refers to an ID in your application, not the project in Harvest. This allows us to associate timesheet entries with your application. 

Sorry for the confusion!
