### ISSUE TITLE
CSP - Content Security Policy

### ISSUE THREAD

**Issue by Artistan** [harvesthq/platform#42]
the button inclusion does not work for me due to CSP...

https://developer.chrome.com/apps/contentSecurityPolicy

![screen shot 2017-08-29 at 2 23 53 pm](https://user-images.githubusercontent.com/801349/29839924-c53edd1a-8cc5-11e7-8b6a-bc860060f480.png)

**Comment by Artistan** [comment]
https://github.com/Artistan/harvest-scripts-integration/blob/master/harvest_git_integration.user.js

**Comment by adunkman** [comment]
It looks like the site that you’re attempting to integrate will uses a Content Security Policy. You’ll need to allow access to `harvestapp.com` in order to integrate — it’s not something that we can allow on our end.

**Comment by Artistan** [comment]
https://chrome.google.com/webstore/detail/content-security-policy-o/lhieoncdgamiiogcllfmboilhgoknmpi

```

[
    ["https://github\\.com", [
        ["img-src", "img-src https://*.harvestapp.com"],
        ["connect-src", "connect-src https://*.harvestapp.com"],
        ["child-src", "child-src https://*.harvestapp.com"],
        ["script-src", "script-src 'unsafe-eval'"]
    ]]
]
```

![screen shot 2017-08-29 at 2 47 07 pm](https://user-images.githubusercontent.com/801349/29840852-fe178288-8cc8-11e7-81f0-22e343ebf888.png)

**Comment by Artistan** [comment]
What's up with just closing this with no feedback? @adunkman ?
You  "embeded" code does not support CSP restrictions.

**Comment by Artistan** [comment]
https://github.com/Artistan/harvest-scripts-integration/blob/master/harvest_git_integration.user.js

this works in gitlabs similar to the chrome plugin.

**Comment by adunkman** [comment]
I’m not sure what to tell you — our script requires access to our servers to function, and based on your screenshot above, a Content Security Policy is preventing the script from accessing our servers. 

You’ll need to change the Content Security Policy to allow access, or the script won’t function. The Content Security Policy is set by the site that you’re integrating into — which unfortunately we at Harvest don’t have access to modify. 

Our Chrome extension modifies Content Security Policies when appropriate, which is how it gets around the restrictions. If something works in GitLab but doesn’t work in other places, I’d expect the sites to have different Content Security Policies.

**Comment by Artistan** [comment]
Thank you for the reply.
