### ISSUE TITLE
IE 11 .initCustomEvent bug

### ISSUE THREAD

**Issue by daniel-meisterlabs** [harvesthq/platform#50]
IE 11 complains, when importing your code via `<script async src="https://platform.harvestapp.com/assets/platform.js"></script>` to setup the harvest button.

Following screenshot shows the error, which is thrown by IE:
![argument-not-optional](https://user-images.githubusercontent.com/52409858/62051075-e30dd200-b212-11e9-8c84-7c4944631b66.PNG)

The `.initCustomEvent()` seems to be the problem. Simply adding an empty object as 4th parameter, solved the issue. So you would have `.initCustomEvent("harvest-event:ready", !0, !0, {})`

**Comment by braddunbar** [comment]
Thanks for reporting this @daniel-meisterlabs! I'll get this fixed up.

**Comment by daniel-meisterlabs** [comment]
Thank you for your time!

I tested this locally and putting an empty object or simply `null` solves the above mentioned error and the Harvest button shows as expected. However, a new problem came up. You can now try to sign-in and the process of signing in seems to work properly, but nothing happens when the sign-in was successful.

In the following screenshot, you can see that the popup tells me, that it was successful and I can close this window. But on doing so, nothing happens. The main window from the Harvest button still shows the sign-in form. Also there are no errors in the console and on other browsers it works fine with the 4th parameter set.
![sign-in_fails](https://user-images.githubusercontent.com/52409858/62109267-341dd480-b2ac-11e9-92f7-9cf8fa2708a9.PNG)

**Comment by braddunbar** [comment]
This should be fixed up now @daniel-meisterlabs. Let me know if that's not the case!

**Comment by braddunbar** [comment]
Hmm…the `CustomEvent` issue is fixed up now, but I can't seem to reproduce the sign in issue above. Would you let me know if it's still present?

**Comment by daniel-meisterlabs** [comment]
I am not quite sure why, but testing on localhost the sign-in fails, but on our production branch everything works perfectly now. Harvest button shows, you can sign-in and track time through IE 11, so thank you very much!

**Comment by braddunbar** [comment]
You're welcome! Let me know if you need anything else. :)
