### ISSUE TITLE
Unminified / Deobfuscated Version of Platform JS

### ISSUE THREAD

**Issue by jasonnissen** [harvesthq/platform#51]
Would it be possible to get an unminified / deobfuscated version of the platform.js file? Google will not accept a Chrome extension referencing the current platform.js file into the webstore.

**Comment by braddunbar** [comment]
Hey @jasonnissen! Sorry about the delay here.

Unfortunately, we don't currently provide an unminified version of the platformjs file. Sorry I don't have better news for you here!

We've had the same issue getting Google to approve our extension and we generally use an iframe with [the widget](https://github.com/harvesthq/platform/blob/master/widget.md). I hope that helps!
