### ISSUE TITLE
Cookies need setting SameSite=None

### ISSUE THREAD

**Issue by yvesvanbroekhoven** [harvesthq/platform#52]
In an upcoming release of Chrome and Firefox, they will prevent cookies without the SameSite setting to be externally accessible.

I tested this with the available browser flags and it seems that this API isn't usable anymore.

Any chance your team is going to fix this anytime soon?

### Current cookies

![](https://www.dropbox.com/s/peesu54xsf2rka3/Screenshot%202020-01-29%2015.03.03.png?raw=1)

### Enable browser flags

**Firefox**

![](https://www.dropbox.com/s/i8w8tpdajc8vojd/Screenshot%202020-01-29%2015.10.42.png?raw=1)

**Chrome**

![](https://www.dropbox.com/s/b6v3hsskmc4nies/Screenshot%202020-01-29%2015.11.57.png?raw=1)

### Error after enabling flags

![](https://www.dropbox.com/s/1b9cl0nrswdcxsu/Screenshot%202020-01-29%2015.05.17.png?raw=1)

### More info

[https://blog.chromium.org/2019/10/developers-get-ready-for-new.html]()

**Comment by cade** [comment]
> Any chance your team is going to fix this anytime soon?

Yep! We're currently working on supporting the `SameSite` attribute (QA will begin today), and we will roll out our changes before Chrome 80's February deadline. Thanks for filing the issue and checking!

**Comment by yvesvanbroekhoven** [comment]
Awesome @cade! 

Just give a sign when I can test 🖖

**Comment by cade** [comment]
@yvesvanbroekhoven We've shipped our support for `SameSite` cookies on Harvest's platform. 

Please note, Firefox's dev tools seem to still be reporting `Unset` (regardless of flag preference settings) even though the `Set-Cookie` header is specifying `SameSite=None` on the cookie. I am seeing the same behavior from the [verification site](https://samesite-sandbox.glitch.me/) that Google links to, so I'm not sure what's going on with Firefox.

Chrome dev tools appear to be correctly reporting `SameSite=None`.

**Comment by cade** [comment]
@yvesvanbroekhoven -- I don't love the route we ended up having to take, but we're currently only serving `SameSite=None` for Chrome 80+, as that is currently the only critical breakage we're facing. You can confirm this behavior in Chrome's beta:

<img width="1092" alt="Screen Shot 2020-01-31 at 1 01 02 PM" src="https://user-images.githubusercontent.com/3403/73566660-03b91d80-442a-11ea-8549-18bb77f4b551.png">

Harvest has required SSL connections and exclusively served `Secure`, encrypted cookies for quite a long time, so whether or not we serve `SameSite=None` to older clients in contexts like platform that require `None` shouldn't have any negative security implications.

We've already migrated many other cookies to `Lax` where possible across our products without issue. We're going to continue to investigate if we can serve `SameSite=None` settings for more browsers without affecting authentication and user experience, but things should continue uninterrupted for Chrome 80 come February. In the mean time, we'll be sure to keep an eye out for Firefox or Edge releases that change their defaults as well.

**Comment by yvesvanbroekhoven** [comment]
Alright @cade, thanks for looking into it. 

If I notice issues in Firefox, I'll let you know!
