### ISSUE TITLE
Harvest platform overwrites Underscore.js

### ISSUE THREAD

**Issue by vahtel** [harvesthq/platform#68]
Background:
We have legacy web app that uses simple jQuery and Underscore.js, Underscore.js string libraries.

Issue: 
https://platform.harvestapp.com/assets/platform.js overwrites the  Underscore.js **_**  object.
<img width="1446" alt="under" src="https://github.com/harvesthq/platform/assets/396759/640c08bf-4541-4952-94ab-53f817a3cbae">

Reproduce:
Use the sample button app https://github.com/harvesthq/platform/blob/master/button.md 

It used to work but I guess something changed from your side.

**Comment by pusewicz** [comment]
@vahtel Thanks for the info! We are working on a fix!

**Comment by pusewicz** [comment]
@vahtel We've pushed an update that should fix the issue. Please let me know if everything is alright on your end!
