### ISSUE TITLE
`SyntaxError: The string did not match the expected pattern.`

### ISSUE THREAD

**Issue by romainmenke** [harvesthq/platform#70]
Seeing errors with message : `SyntaxError: The string did not match the expected pattern.` in Safari.

<img width="618" alt="Screenshot 2024-01-02 at 10 43 19" src="https://github.com/harvesthq/platform/assets/11521496/5206cb65-e634-4b0e-bf08-9f447c74deeb">

_Sorry for the screenshot and not providing a text version of the stacktrace. Safari doesn't make it possible to copy/paste stacktraces as text._

------

The error happens in 

```
  if (accessToken && accountId) {
    postCredentialsToChromeExtension(accessToken, accountId)
  }
```

Which seems logical because Safari won't have any chrome extensions 😅

**Comment by pusewicz** [comment]
Thanks @romainmenke, we're going to look into this!

**Comment by romainmenke** [comment]
Hi @pusewicz,

Was this fixed and if so was that fix already deployed?

It is still broken on my end with the same error.

**Comment by pusewicz** [comment]
@romainmenke We pushed one more change that should address this. Would you mind giving it a go?

**Comment by romainmenke** [comment]
It is working again!
Thank you so much :)
