### ISSUE TITLE
Const identifier reassignment bug

### ISSUE THREAD

**Issue by ARahimKhan** [harvesthq/platform#71]
We are pulling a platform.js script from the CDN provided in your readme but it stopped working very recently (within last 24 hours). The issue seems to be a const reassignment in the addTimers function. For now, I have resolved this by patching the raw js file and changing `const o` to `let o`

I am attaching images for your reference

Console error:
<img width="464" alt="Screenshot 2024-01-12 at 10 02 40 AM" src="https://github.com/harvesthq/platform/assets/48161465/8f21cd81-7ebb-4265-9b70-cb7023e48bcd">

Before patch:
<img width="313" alt="Screenshot 2024-01-12 at 2 10 38 PM" src="https://github.com/harvesthq/platform/assets/48161465/1e68f8ef-027f-4d7e-813b-dcb9c90283cb">

After patch:
<img width="313" alt="Screenshot 2024-01-12 at 2 10 29 PM" src="https://github.com/harvesthq/platform/assets/48161465/7e8065b9-0fbc-4c19-9669-d245a6e83937">

Please do let me know if this is expected behaviour or a bug and if it is expected, let me know how I can resolve it without patching the script

**Comment by pusewicz** [comment]
@ARahimKhan Thank you for raising this issue. We have reverted a recent change that introduced this regression. Can you confirm everything is in order?

**Comment by ARahimKhan** [comment]
Yes, the issue seems to be fixed now, thanks for the quick resolution
